#!/bin/bash
total 20
-rw-r--r-- 1 root root 85 Apr 13 15:10 0-current_working_directory
-rw-r--r-- 1 root root 16 Apr 13 15:01 1-listit
-rw-r--r-- 1 root root 15 Apr 13 15:19 2-bring_me_home
-rw-r--r-- 1 root root 18 Apr 13 15:26 3-listfiles
-rw-r--r-- 1 root root 19 Apr 13 14:43 README.md
